checkpoint_dir: /home/ethrc/Desktop/training/checkpoints
num_machines: 1
multi_gpu: false
num_processes: 1
mixed_precision: bf16
dynamo_backend: inductor
batch_size: 38
steps: 20000
optimizer_lr: 5e-5
num_workers: 12
video_backend: torchcodec
policy_device: cuda
