dataset_repo_id: ETHRC/towelspring26_2
policy_repo_id: ETHRC/act-towelspring26_2
output_dir: /home/ethrc/Desktop/training/checkpoints/act/run2
job_name: act_training_1
num_machines: 1
multi_gpu: false
num_processes: 1
mixed_precision: bf16
dynamo_backend: "no"
batch_size: 20
steps: 40000
optimizer_lr: 1.5e-5
num_workers: 12
video_backend: torchcodec
policy_device: cuda
