checkpoint_dir: /checkpoints
num_machines: 1
multi_gpu: true
num_processes: 4
mixed_precision: bf16
dynamo_backend: inductor
batch_size: 96
steps: 2100
optimizer_lr: 4.8e-4
num_workers: 10
video_backend: torchcodec
policy_device: cuda
