checkpoint_dir: /checkpoints
num_machines: 1
multi_gpu: true
num_processes: 4
mixed_precision: bf16
dynamo_backend: "no"
batch_size: 24
steps: 20000
optimizer_lr: 1e-5
num_workers: 2
video_backend: torchcodec
policy_device: cuda
