checkpoint_dir: /checkpoints
num_machines: 1
multi_gpu: false
num_processes: 1
mixed_precision: bf16
dynamo_backend: "no"
batch_size: 48
steps: 5000
optimizer_lr: 5e-5
num_workers: 8
video_backend: torchcodec
policy_device: cuda
